#!/bin/bash

if [ $# -gt 1 ]
then
    echo "usage: arch [archive_name]"
fi

archdir='archive'
archno=$( ls $archdir | wc -l )
archno=$((archno/4))
datafile='syndata.txt'
datacsv='syndata.csv'
fetchfile='synfetchresults.txt'
fetchcsv='synfetchresults.csv'

if [ $# -eq 1 ]
then
    archno=$1
fi

srcdir='resultstats/agg'
echo 'creating archive '$archno
cp -uv $srcdir'/'$datafile $archdir'/sd'$archno'.txt'
cp -uv $srcdir'/'$fetchfile $archdir'/sf'$archno'.txt'
cp -uv $srcdir'/'$datacsv $archdir'/sd'$archno'.csv'
cp -uv $srcdir'/'$fetchcsv $archdir'/sf'$archno'.csv'
